#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/inmem
#
# IDENTIFICATION
#    src/backend/access/inmem/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/inmem
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = inmem_handler.o

include $(top_srcdir)/src/backend/common.mk
